services:
  postgres:
    image: postgres:18
    container_name: course_platform_db
    environment:
      POSTGRES_DB: course_platform
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d course_platform"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  minio:
    image: minio/minio
    container_name: course_platform_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped

  backend:
    build: .
    container_name: course_platform_backend  # ← переименован
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/course_platform
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
      MINIO_BUCKET: course-platform
      JWT_SECRET: mySecretKeyForJWTGeneration2026WithAtLeast32CharactersLong  # ← добавлено
      JWT_EXPIRATION: 86400000
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build: ../course-platform-frontend
    container_name: course_platform_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8080
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:
  minio_data:

networks:
  app-network:
    driver: bridge